#!/bin/bash
export CTRL_SERVER_IP='192.168.11.10'
export WAFL_DEVICE_NAMES='0'
export WAFL_DEVICE_IPS='wafl.hongo.wide.ad.jp'
export WAFL_DEVICE_CTRL_PORT=50001
export WAFL_DEVICE_P2P_PORT=50002

# Account-related details
export USER='denjo'
export DEPLOYMENT_LOCATION='/home/denjo/workspace/ktakahashi'
export EXPERIMENT_NAME='wafl_test_experiment'
