[project]
name = "wafl-testbed"
version = "0.1.0"
description = "The WAFL Emulation Testbed project, launched in April 2025, is trying to develop a research platform for WAFL's device-to-device collaborative learning over real TCP/IP-based communications."
readme = "README.md"
requires-python = "==3.11.4"
dependencies = [
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "lz4>=4.3.0",
    "zfec>=1.5.0",
    "matplotlib>=3.7.0",
    "psutil>=5.9.0",
    "paramiko>=3.0.0",
    "seaborn>=0.13.2",
    "functions>=0.7.0",
    "tqdm>=4.67.1",
    "traci>=1.25.0",
    "pre-commit>=4.5.0",
    "wandb>=0.16.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "wafl"}

[tool.setuptools.packages.find]
where = ["wafl"]

[tool.ruff]
target-version = "py311"
builtins = ["_"]
exclude = [
    ".git",
    ".venv",
    "assets",
]
indent-width = 4
line-length = 256

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = ["E", "F", "I"]
