name: WAFL-Testbed
on:
    push:
        branches:
            - testbed-develop
            - testbed-develop-ctrl
            - testbed-develop-wafl
    pull_request:
        branches:
            - testbed-develop
            - testbed-develop-ctrl
            - testbed-develop-wafl
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: astral-sh/ruff-action@main
              with:
                  version: 0.12.0
                  args: check --select E,F,I --output-format github
                  src: "./WAFL-Testbed"

